### ISSUE TITLE
mappingV4 is not working

### ISSUE THREAD

**Issue by joseboretto** [LoicMahieu/mimetype-to-fontawesome#14]
Hi, i was debuging your library and mappingV4 is not working because in this line
https://github.com/LoicMahieu/mimetype-to-fontawesome/blob/master/index.js#L89

in the case of mimetype === 'text/plain' 
the variable icon has the value "fa-file-alt" instead of "file-alt".

You should use the icon value without prefix.

**Comment by joseboretto** [comment]
There is another minor bug with the regex that map 'file-archive'
This mime type does not match your expression 'application/x-rar'

**Comment by LoicMahieu** [comment]
Hi @joseboretto 
Sorry to be late. I don't have time to review my github notification very often ;)

I don't use actively this package anymore. The mapping v4 has been made by @ngoue in https://github.com/LoicMahieu/mimetype-to-fontawesome/commit/857a595f3331519845694a5504a50ec3b6dcd2d8#diff-168726dbe96b3ce427e7fedce31bb0bc

Please create a pull request with the change you want, it'll open discussion about that.

Thanks.
